=begin
#Streaming Availability API

#Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 60 countries!

The version of the OpenAPI document: 4.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'date'
require 'time'

module OpenapiClient
  class ChangeType
    NEW = "new".freeze
    REMOVED = "removed".freeze
    UPDATED = "updated".freeze
    EXPIRING = "expiring".freeze
    UPCOMING = "upcoming".freeze

    def self.all_vars
      @all_vars ||= [NEW, REMOVED, UPDATED, EXPIRING, UPCOMING].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ChangeType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ChangeType"
    end
  end
end
