=begin
#Streaming Availability API

#Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 60 countries!

The version of the OpenAPI document: 4.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'date'
require 'time'

module OpenapiClient
  # Image set of a show.
  class ShowImageSet
    # Vertical poster of the show.
    attr_accessor :vertical_poster

    # Horizontal poster of the show.
    attr_accessor :horizontal_poster

    # Vertical backdrop of the show.
    attr_accessor :vertical_backdrop

    # Horizontal backdrop of the show.
    attr_accessor :horizontal_backdrop

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'vertical_poster' => :'verticalPoster',
        :'horizontal_poster' => :'horizontalPoster',
        :'vertical_backdrop' => :'verticalBackdrop',
        :'horizontal_backdrop' => :'horizontalBackdrop'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'vertical_poster' => :'VerticalImage',
        :'horizontal_poster' => :'HorizontalImage',
        :'vertical_backdrop' => :'VerticalImage',
        :'horizontal_backdrop' => :'HorizontalImage'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::ShowImageSet` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::ShowImageSet`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'vertical_poster')
        self.vertical_poster = attributes[:'vertical_poster']
      else
        self.vertical_poster = nil
      end

      if attributes.key?(:'horizontal_poster')
        self.horizontal_poster = attributes[:'horizontal_poster']
      else
        self.horizontal_poster = nil
      end

      if attributes.key?(:'vertical_backdrop')
        self.vertical_backdrop = attributes[:'vertical_backdrop']
      end

      if attributes.key?(:'horizontal_backdrop')
        self.horizontal_backdrop = attributes[:'horizontal_backdrop']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @vertical_poster.nil?
        invalid_properties.push('invalid value for "vertical_poster", vertical_poster cannot be nil.')
      end

      if @horizontal_poster.nil?
        invalid_properties.push('invalid value for "horizontal_poster", horizontal_poster cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @vertical_poster.nil?
      return false if @horizontal_poster.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] vertical_poster Value to be assigned
    def vertical_poster=(vertical_poster)
      if vertical_poster.nil?
        fail ArgumentError, 'vertical_poster cannot be nil'
      end

      @vertical_poster = vertical_poster
    end

    # Custom attribute writer method with validation
    # @param [Object] horizontal_poster Value to be assigned
    def horizontal_poster=(horizontal_poster)
      if horizontal_poster.nil?
        fail ArgumentError, 'horizontal_poster cannot be nil'
      end

      @horizontal_poster = horizontal_poster
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          vertical_poster == o.vertical_poster &&
          horizontal_poster == o.horizontal_poster &&
          vertical_backdrop == o.vertical_backdrop &&
          horizontal_backdrop == o.horizontal_backdrop
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [vertical_poster, horizontal_poster, vertical_backdrop, horizontal_backdrop].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
