=begin
#Streaming Availability API

#Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 60 countries!

The version of the OpenAPI document: 4.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'date'
require 'time'

module OpenapiClient
  # Availability of the streaming option types in the service.
  class StreamingOptionTypes
    # Whether there are shows available via an addon/channel subscription.
    attr_accessor :addon

    # Whether there are shows available to buy.
    attr_accessor :buy

    # Whether there are shows available for rental.
    attr_accessor :rent

    # Whether there are free shows to watch.
    attr_accessor :free

    # Whether there are shows available via a paid subscription plan.
    attr_accessor :subscription

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'addon' => :'addon',
        :'buy' => :'buy',
        :'rent' => :'rent',
        :'free' => :'free',
        :'subscription' => :'subscription'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'addon' => :'Boolean',
        :'buy' => :'Boolean',
        :'rent' => :'Boolean',
        :'free' => :'Boolean',
        :'subscription' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::StreamingOptionTypes` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::StreamingOptionTypes`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'addon')
        self.addon = attributes[:'addon']
      else
        self.addon = nil
      end

      if attributes.key?(:'buy')
        self.buy = attributes[:'buy']
      else
        self.buy = nil
      end

      if attributes.key?(:'rent')
        self.rent = attributes[:'rent']
      else
        self.rent = nil
      end

      if attributes.key?(:'free')
        self.free = attributes[:'free']
      else
        self.free = nil
      end

      if attributes.key?(:'subscription')
        self.subscription = attributes[:'subscription']
      else
        self.subscription = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @addon.nil?
        invalid_properties.push('invalid value for "addon", addon cannot be nil.')
      end

      if @buy.nil?
        invalid_properties.push('invalid value for "buy", buy cannot be nil.')
      end

      if @rent.nil?
        invalid_properties.push('invalid value for "rent", rent cannot be nil.')
      end

      if @free.nil?
        invalid_properties.push('invalid value for "free", free cannot be nil.')
      end

      if @subscription.nil?
        invalid_properties.push('invalid value for "subscription", subscription cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @addon.nil?
      return false if @buy.nil?
      return false if @rent.nil?
      return false if @free.nil?
      return false if @subscription.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] addon Value to be assigned
    def addon=(addon)
      if addon.nil?
        fail ArgumentError, 'addon cannot be nil'
      end

      @addon = addon
    end

    # Custom attribute writer method with validation
    # @param [Object] buy Value to be assigned
    def buy=(buy)
      if buy.nil?
        fail ArgumentError, 'buy cannot be nil'
      end

      @buy = buy
    end

    # Custom attribute writer method with validation
    # @param [Object] rent Value to be assigned
    def rent=(rent)
      if rent.nil?
        fail ArgumentError, 'rent cannot be nil'
      end

      @rent = rent
    end

    # Custom attribute writer method with validation
    # @param [Object] free Value to be assigned
    def free=(free)
      if free.nil?
        fail ArgumentError, 'free cannot be nil'
      end

      @free = free
    end

    # Custom attribute writer method with validation
    # @param [Object] subscription Value to be assigned
    def subscription=(subscription)
      if subscription.nil?
        fail ArgumentError, 'subscription cannot be nil'
      end

      @subscription = subscription
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          addon == o.addon &&
          buy == o.buy &&
          rent == o.rent &&
          free == o.free &&
          subscription == o.subscription
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [addon, buy, rent, free, subscription].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
