=begin
#Streaming Availability API

#Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 60 countries!

The version of the OpenAPI document: 4.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::GenresApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GenresApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::GenresApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GenresApi' do
    it 'should create an instance of GenresApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::GenresApi)
    end
  end

  # unit tests for get_genres
  # Get all Genres
  # Get the list of supported genres.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :output_language [ISO 639-1 code](https://en.wikipedia.org/wiki/ISO_639-1) of the output language. Determines in which language the output  will be in. 
  # @return [Array<Genre>]
  describe 'get_genres test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
