=begin
#Streaming Availability API

#Streaming Availability API allows getting streaming availability information of movies and series; and querying the list of available shows on streaming services such as Netflix, Disney+, Apple TV, Max and Hulu across 60 countries!

The version of the OpenAPI document: 4.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::OrderDirection
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::OrderDirection do
  let(:instance) { OpenapiClient::OrderDirection.new }

  describe 'test an instance of OrderDirection' do
    it 'should create an instance of OrderDirection' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::OrderDirection)
    end
  end

end
